#!/bin/bash
set -euxo pipefail

# echo "$INSTRUQT_USER_NAME running challenge setup script on $INSTRUQT_CHALLENGE_ID"

# Initialize the home directory with the Dockerfile
mkdir /newrelic
set-workdir /newrelic
git clone https://github.com/ptahdunbar/o11y-as-code-terraform /newrelic